spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: demo
    password: demo
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
  application:
    name: demo-api

server:
  port: 8088
  servlet:
    context-path: /saqaya/demo/v1/api

logging:
  file:
    name: logs/saqaya-demo.log

salt-key: 450d0b0db2bcf4adde5032eca1a7c416e560cf44